// ---------------------------------------------------------------------------------------------
//  Copyright (c) 2026, Jiaqi (0x7c13) Liu. All rights reserved.
//  See LICENSE file in the project root for license information.
// ---------------------------------------------------------------------------------------------

namespace WinUIEditor
{
	[default_interface]
	runtimeclass EditorUtf8Reader : Windows.Foundation.IClosable
	{
		UInt64 Length { get; };
		UInt64 Sequence { get; };
		Windows.Storage.Streams.IBuffer Read(Int64 offset, Int32 maxBytes);
		Windows.Foundation.IAsyncOperation<Windows.Storage.Streams.IBuffer> ReadAsync(Int64 offset, Int32 maxBytes);
	}
}
